### ISSUE TITLE
Can you add this app to balena hub?

### ISSUE THREAD

**Issue by swingstate** [klutchell/balena-photoprism#1]
And do you still maintain it?

**Comment by klutchell** [comment]
Were you looking for it as a joinable Fleet, or as a forkable Project on Hub?

I can do the latter, but I'm not running this project personally anymore so it wouldn't get many updates from me as a fleet.

There are also a TON of environment variables for tweaking the behaviour, which wouldn't be available to users of the public fleet. Not yet anyway, we would need to expose those settings another way.

**Comment by swingstate** [comment]
well, probably both. I am using the app for larger picture libraries and wanted to move that to a more power efficient setup, to a Raspberry probably. 
Since I also sponsor the app devs I wouldn't mind to ask if they would be open to fork/maintain it.

**Comment by klutchell** [comment]
Thanks for sharing your use case!

> I am using the app for larger picture libraries and wanted to move that to a more power efficient setup, to a Raspberry probably.

It doesn't need to be in balenaHub for this to be an option, but it definitely makes it easier. Have you tried the deploy button on the readme? If there is anything I can do to help get this part off the ground just let me know. Maybe it just needs a clean up as I haven't tried running it in some time.

> Since I also sponsor the app devs I wouldn't mind to ask if they would be open to fork/maintain it.

This would honestly be ideal, as I really like the software but I don't have the bandwidth to maintain it right now. I encourage anyone that is interested to fork this repo and take over maintenance or publish to balenaHub!
